Create python package
eclipse-velocitas/vehicle-model-generator pull request #30
Opened 2023-01-31 17:57 UTC by BjoernAtBosch

## Describe your changes

Make model generator available as a Python package

## Issue ticket number and link

AD#_12516_

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-02-02 09:40 UTC, dennismeister93 requested changes

2023-02-02 09:40 UTC, dennismeister93 commented on setup.cfg
> +    vss-tools @ git+https://github.com/covesa/vss-tools@v3.0
Question: When using/distributing the Model Generator as a package, is it sufficient to specify only this single one dependency here on the setup.cfg? Are the other needed dependency picked up from the requirements.txt by default?

2023-02-02 09:40 UTC, dennismeister93 commented on setup.py
> +from setuptools import setup
When running the example command from the root of the repo/devcontainer

`python3 gen_vehicle_model.py -I ./vehicle_signal_specification/spec ./vehicle_signal_specification/spec/VehicleSignalSpecification.vspec`

the setup.py will be overwritten to e.g.:

```
from setuptools import find_packages, setup  # type: ignore

setup(
    name="None",
    version="0.1.0",
    description="Vehicle Model",
    packages=find_packages(),
    zip_safe=False,
)
```

should we take care about this?

2023-02-02 09:40 UTC, dennismeister93 commented on setup.cfg
> +    vss-tools @ git+https://github.com/covesa/vss-tools@v3.0
Or probably the dependencies in the requirements.txt are not needed to run the generator.. :D

2023-02-02 09:54 UTC, BjoernAtBosch commented on setup.cfg
> +    vss-tools @ git+https://github.com/covesa/vss-tools@v3.0
Yes, the other dependencies are relevant for dev-container, only

2023-02-02 10:48 UTC, BjoernAtBosch commented on setup.py
> +from setuptools import setup
Yes, of course we should.
I first recognized that yesterday. I'm not sure why I didn't notice that/it didn't occure(?) before. Maybe because I mostly tried with cpp ...
It seems being an discrepancy between cpp and python generator. The Python one seems not to fit to documentation ...

2023-02-03 12:45 UTC, BjoernAtBosch commented on setup.py
> +from setuptools import setup
Fixed

2023-02-03 12:54 UTC, BjoernAtBosch commented
I've fixed the model generator for Python now. Means:
* --target-folder now actually defines the folder where the model is generated into, and
* --name defines the root package name of the model (which also results in a same named subfolder below target-folder.
* setup.py is generated into target-folder
Fixing cpp model generator is in progress but needs further discussion:
* Shall namespace hierarchy meet folder structure?
General:
* Shall namespace/package names always be lower case or  mixed case (as currently)?
* Generated Python files in vehicle_model_python repo contain license header (incl. copyright), but generated files do not. Why?
* What about services?

2023-02-07 08:44 UTC, dennismeister93 approved these changes
tested, works fine, lgtm!

2023-02-07 09:35 UTC, merged