Fix cpp generator
eclipse-velocitas/vehicle-model-generator pull request #31
Opened 2023-02-03 16:39 UTC by BjoernAtBosch

## Describe your changes

Fix C++ generator using matching namespace/folder structure

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-02-14 11:39 UTC, BjoernAtBosch commented
@doosuu:
I would go here for version 0.3.0 because of incompatible change in model generation.

2023-02-14 14:10 UTC, doosuu requested changes

2023-02-14 14:10 UTC, doosuu commented on sdv/model_generator/cpp/cpp_generator.py
> +        if "::" in root_namespace:
For reduction of complexity: Introduce `__get_root_namespace_list(namespace: str) -> list[str]`?

2023-02-14 14:10 UTC, doosuu commented on sdv/model_generator/cpp/cpp_generator.py
> +                path = os.path.join("", *self.__to_folder_names(child_namespace_list))
You can simply call `os.path.join(*self.__to_folder_names(child_namespace_list))` the empty string as first argument is superfluous

2023-02-14 14:10 UTC, doosuu commented on sdv/model_generator/cpp/cpp_generator.py
> +                self.includes.add(f"{path}/{child.name}")
Above you use `os.path.join` to do path based joining, here you rely on the literal `/` I would recommend to append `child_name` to the list before calling `os.path.join` to get the full path via join

2023-02-14 14:10 UTC, doosuu commented on sdv/model_generator/utils.py
> +def to_snake_case(camel_case_input):
I expect that this only works for converting camel case to snake case. Maybe `camel_to_snake_case(input: str) -> str` would be a better way of calling this? Also please add type annotations

2023-02-14 15:42 UTC, BjoernAtBosch commented on sdv/model_generator/cpp/cpp_generator.py
> +                path = os.path.join("", *self.__to_folder_names(child_namespace_list))
Thought, I tried that and was not working. But yes, works. 
Thx!

2023-02-15 08:15 UTC, doosuu approved these changes
LGTM

2023-02-15 08:38 UTC, merged