[10945] Adapt to latest VSS tools changes. Rename data_type to dataty…
eclipse-velocitas/vehicle-model-generator pull request #5
Opened 2022-08-15 13:02 UTC by dennismeister93

…pe. Rename break_on_noncore_attribute to break_on_unknown_attribute

Signed-off-by: Dennis Meister <dennis.meister@bosch-softtec.com>

## Describe your changes

Adapting vehicle-model-generator to changes in https://github.com/COVESA/vss-tools/commit/088791c15ac6afc18389e6446c06d1e33bd62032#diff-bd7a7e19458ea183d09243c6b66711908091c977580d1564a1c9f4e6e7c0c63aL93

## Issue ticket number and link

[AB#_[10945]_](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/10945)
https://github.com/eclipse-velocitas/vehicle-model-generator/issues/4

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-08-16 10:41 UTC, emsameen requested changes
I approve the changes, LGTM. However, I would move the status to pending until the contributor approval is ready and the source of the PR is adjusted.

2022-08-17 09:30 UTC, MP91 requested changes

2022-08-17 09:30 UTC, MP91 commented on gen_vehicle_model.py
> +            break_on_unknown_attribute=strict,
the attribute is just a bool so we should set it to true
```suggestion
            break_on_unknown_attribute=True,
```

2022-08-17 10:15 UTC, dennismeister93 commented
Closed due to official PR from SDV org https://github.com/eclipse-velocitas/vehicle-model-generator/pull/6

2022-08-17 10:15 UTC, closed without merging